services:
  app:
    build:
      context: .      
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicalsoftdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy  # Espera que la base de datos esté lista antes de iniciar

  db:
    image: postgres:13
    container_name: medicalsoftdb
    restart: always  # Asegura que el contenedor se reinicie si falla
    environment:
      POSTGRES_DB: medicalsoftdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistencia de datos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

